### ISSUE TITLE
youtube url

### ISSUE THREAD

**Issue by martingg88** [tusharmath/Multi-threaded-downloader#39]
seem like it doesn't download youtube mp4 video. You can try with following link and it doesn't work. any idea? FYI. the following link will work with wget. Maybe we need the --no-check-certificate option?

https://lh3.googleusercontent.com/xTMukQfobC193nsiO3K78vhxoaLyt5trzxOk4V3Wmw=m18

**Comment by tusharmath** [comment]
@martingg88 The real problem is that this module doesn't support HTTPS out of the box. It would be great if you could send a pull request for the same or I can make you the collaborater. I am also thinking of re-writing this module from scratch.

**Comment by martingg88** [comment]
i'm regret to tell you that i have not idea how to write this module. sorry

**Comment by martingg88** [comment]
what about you give me the system flow for this library, so i can try to write to support HTTPS?

**Comment by tusharmath** [comment]
@martingg88 I have made a lot of changes since your last message. Checkout the [develop branch](https://github.com/tusharmath/Multi-threaded-downloader/blob/develop/index.js). 

Its a complete re-write, using a pub-sub approach. Unfortunately all the features have not been implemented. Though this supports HTTPS, it doesn't support stopping of a download or download concurrently, both of which should be extremely easy to implement. It would be great if you can continue from here instead of the master branch. The code is concise and much easier to read.

**Comment by martingg88** [comment]
what about integrate with this "node-fast-download" and add the level to make it support of multiple thread?

**Comment by tusharmath** [comment]
@martingg88 I have been really busy man. In between jobs and so I really apologise for ruining the trust you have put in this piece of software. I know you must be really pissed. I will fix this I promise. Give me sometime.

**Comment by martingg88** [comment]
don't worry guy. i'm understand your situation. let's take your time. 
Many thanks for your effort.

**Comment by tusharmath** [comment]
This issue is resolved in the develop branch, could you try once again, so that I could close this ticket?

**Comment by tusharmath** [comment]
I was able to download files over https sucessfully. Hence closing the ticket
