### ISSUE TITLE
Transfer-Encoding: chunked data can't download

### ISSUE THREAD

**Issue by ghost** [tusharmath/Multi-threaded-downloader#45]
library checks content-length but chunked data is not included.

**Comment by tusharmath** [comment]
This would require a completely different approach. How would one know if the download was completed for example?

**Comment by Phoary** [comment]
when download is completed it goes re-download with ".mtd" extension and file size is 0.

how about checks header first and find if it is Transfer-Encoding : chunked.
Then, request body and check body length.

**Comment by tusharmath** [comment]
Content-Length would not be available for chunked responses. Body length can not be used because then I would have to save the complete resource in memory which will be expensive.

This would only work if the server supports range headers with chunked data. Though technically its possible, I wonder if its been implemented in any server.

**Comment by tusharmath** [comment]
You won't be able to start and resume a download, right?
